### PR TITLE
Docs Refresh

### LINKED ISSUE #2: Refresh documentation
This is an ongoing project, with files collaborated on in [Google Docs](https://drive.google.com/drive/folders/10nsLPokttFjG9g4x4mLBYNkTyO0izy5H).

### PR DESCRIPTION
**Pull request by bluesabre**
Creating a draft PR so remaining tasks can be tracked.

Task list from [Google Drive](https://drive.google.com/drive/folders/10nsLPokttFjG9g4x4mLBYNkTyO0izy5H)

- [x] Homepage
- [x] 1. Welcome
- [x] 2. Credits and License
- [x] 3. Appendix B - Creative Commons
- [x] Chapter 1. What is Xubuntu?
- [x] Chapter 2. Installation
- [x] Chapter 3. Introduction
- [x] Chapter 4. Default Applications
- [x] Chapter 5. Software Management
- [x] Chapter 6. Settings - Personalization
- [x] Chapter 7. Settings - Hardware
- [x] Chapter 8. Settings - Connectivity
- [x] Chapter 9. Printing and Scanning
- [x] Chapter 10. User Management
- [x] ~Chapter 11. Disks~
- [x] Chapter 12. File Management
- [x] ~Chapter 13. Laptops~
- [x] Chapter 14. Media applications
- [x] Chapter 15. Migrating
- [x] Chapter 16. Troubleshooting
- [x] Chapter 17. Upgrading

### CODE REVIEW

**Comment by bluesabre** [comment]
@philipzae Please let me know where we stand on this currently. Thanks!

**Comment by philipzae** [comment]
@bluesabre sorry for the delayed reply. I will restart work on this next week once i get access to my desktop and hopefully can finish them all during August.

You can add checks to '1. Welcome' and '2. Credits and License' as they were [already done](https://github.com/philipzae/xubuntu-docs/commit/e5eb54347f491921ba01415948b15d256d3e6b7b).

Not sure where the file for '3. Appendix B - Creative Commons' .xml file is, but it needs to be updated with the text from version 4.0. https://creativecommons.org/licenses/by-sa/4.0/

**Comment by bluesabre** [comment]
@Xubuntu/xubuntu-team The docbook migration is finally complete! Anybody want to look over it before we merge into master? These docs have been deployed to: https://xubuntu.github.io/xubuntu-docs/

**Comment by bluesabre** [comment]
Feedback from IRC:

Unit193: https://xubuntu.github.io/xubuntu-docs/user/C/internet-networks.html for example seems a bit "odd", shouldn't be using ifconfig, etc

krytarik: 1.) the webchat links are still from old Freenode, and 2.) all the icon additions in the user docs should have gone into the xubuntu-user.ent rather than the -common one.

**Comment by skellat** [comment]
The screenshots in Chapter 2 need spacers between them.  The successive screenshots of the initial boot of installation need just a bit of spacing so it doesn't look like a vast sea of darkness.  Other than that I don't see any obvious issues.  Make sure you generate the PDF files, though.

**Comment by bluesabre** [comment]
> The screenshots in Chapter 2 need spacers between them. The successive screenshots of the initial boot of installation need just a bit of spacing so it doesn't look like a vast sea of darkness. Other than that I don't see any obvious issues. Make sure you generate the PDF files, though.

I added some default margins for screenshots which helped that out substantially. I also did a test PDF build and fixed two images that did not fit correctly.

Anything else? @Xubuntu/xubuntu-team?

**Pull request merged**
