### PR TITLE
Docs refresh

### PR DESCRIPTION
**Pull request by JT252**
Chapter 6 3rd try.

### CODE REVIEW

**Comment by bluesabre** [comment]
Bad merge? Duplicate of #15 and #17. Please let me know which is the active pull request.

**Comment by bluesabre** [comment]
Please review and address the failed validation. Some examples:

> settings-personalization.xml:16: element chapter: validity error : Element chapter content does not follow the DTD, expecting (beginpage? , chapterinfo? , (title , subtitle? , titleabbrev?) , (toc | lot | index | glossary | bibliography)* , tocchap? , (((calloutlist | glosslist | itemizedlist | orderedlist | segmentedlist | simplelist | variablelist | caution | important | note | tip | warning | literallayout | programlisting | programlistingco | screen | screenco | screenshot | synopsis | cmdsynopsis | funcsynopsis | classsynopsis | fieldsynopsis | constructorsynopsis | destructorsynopsis | methodsynopsis | formalpara | para | simpara | address | blockquote | graphic | graphicco | mediaobject | mediaobjectco | informalequation | informalexample | informalfigure | informaltable | equation | example | figure | table | msgset | procedure | sidebar | qandaset | task | anchor | bridgehead | remark | highlights | abstract | authorblurb | epigraph | indexterm | beginpage | xi:include)+ , (sect1* | refentry* | simplesect* | section*)) | sect1+ | refentry+ | simplesect+ | section+) , (toc | lot | index | glossary | bibliography)*), got (title para para CDATA section section section section section section section CDATA para para CDATA)

Docbook is strict and requires that the documentation follows a specific pattern. I think the items that are triggering this error are the para blocks after the section blocks. I think moving those last paras into sections should resolve.

> settings-personalization.xml:30: element section: validity error : Syntax of value for attribute id of section is not valid

Sections ids should be lowercase and have no spaces. Use hyphens instead.

> settings-personalization.xml:184: element itemizedlist: validity error : Element itemizedlist content does not follow the DTD, expecting (blockinfo? , (title , titleabbrev?)? , (caution | important | note | tip | warning | literallayout | programlisting | programlistingco | screen | screenco | screenshot | synopsis | cmdsynopsis | funcsynopsis | classsynopsis | fieldsynopsis | constructorsynopsis | destructorsynopsis | methodsynopsis | formalpara | para | simpara | address | blockquote | graphic | graphicco | mediaobject | mediaobjectco | informalequation | informalexample | informalfigure | informaltable | anchor | bridgehead | remark | highlights | abstract | authorblurb | epigraph | indexterm | beginpage)* , listitem+), got (listitem CDATA listitem CDATA listitem CDATA)

I think the CDATA blocks have to be inside listitems.

**Comment by JT252** [comment]
I'm going to guess it's the last one. Happy Easter.

**Comment by bluesabre** [comment]
Closing in favor of #19

**Pull request closed without merging**
