### PR TITLE
Chapter 6

### PR DESCRIPTION
**Pull request by bluesabre**
Cleanup and consolidation of previous attempts #14 #15 #16 #17

### CODE REVIEW

**Comment by bluesabre** [comment]
@JT252 Can you review and verify these are the changes you were going for?

@philipzae Since you're a bit more familiar with how we structure the docs now, can you review and confirm this looks good?

**Comment by JT252** [comment]
Yes, but why are the corrections in the wording so different from what I'm
transcribing in the gdoc?

Example;

old_<section id="panel-personalization">
new_<section id="settings-personalization-panel">

John...

**Comment by bluesabre** [comment]
@JT252 This is because the section ids have to be unique, not only on the individual file, but across multiple files. To achieve this, I chose a unique pattern that matched the sections and subsections. You can use the `validate.sh` script to quickly run validation before committing to make sure it checks out.

```
./scripts/validate.sh user-docs/C/settings-personalization.xml
```

**Comment by JT252** [comment]
How would I have known this?

**Comment by JT252** [comment]
Also, when I tested the xml as described in this document:
https://github.com/Xubuntu/xubuntu-docs/wiki after many modifications, the
test passed and converted the file to a html file. When I run this file, I
get a bunch of errors:

***@***.***:~/xubuntu-docs/user-docs$ cd ..
***@***.***:~/xubuntu-docs$ ./scripts/validate.sh
user-docs/C/settings-personalization.xml
Validating user-docs/C/settings-personalization.xml ...
user-docs/C/settings-personalization.xml:16: element chapter: validity
error : Element chapter content does not follow the DTD, expecting
(beginpage? , chapterinfo? , (title , subtitle? , titleabbrev?) , (toc |
lot | index | glossary | bibliography)* , tocchap? , (((calloutlist |
glosslist | itemizedlist | orderedlist | segmentedlist | simplelist |
variablelist | caution | important | note | tip | warning | literallayout |
programlisting | programlistingco | screen | screenco | screenshot |
synopsis | cmdsynopsis | funcsynopsis | classsynopsis | fieldsynopsis |
constructorsynopsis | destructorsynopsis | methodsynopsis | formalpara |
para | simpara | address | blockquote | graphic | graphicco | mediaobject |
mediaobjectco | informalequation | informalexample | informalfigure |
informaltable | equation | example | figure | table | msgset | procedure |
sidebar | qandaset | task | anchor | bridgehead | remark | highlights |
abstract | authorblurb | epigraph | indexterm | beginpage | xi:include)+ ,
(sect1* | refentry* | simplesect* | section*)) | sect1+ | refentry+ |
simplesect+ | section+) , (toc | lot | index | glossary | bibliography)*),
got (title para para CDATA section section section section section section
section CDATA para para CDATA)
user-docs/C/settings-personalization.xml:30: element section: validity
error : Syntax of value for attribute id of section is not valid
user-docs/C/settings-personalization.xml:57: element section: validity
error : Element section content does not follow the DTD, expecting
(sectioninfo? , (title , subtitle? , titleabbrev?) , (toc | lot | index |
glossary | bibliography)* , (((calloutlist | glosslist | itemizedlist |
orderedlist | segmentedlist | simplelist | variablelist | caution |
important | note | tip | warning | literallayout | programlisting |
programlistingco | screen | screenco | screenshot | synopsis | cmdsynopsis
| funcsynopsis | classsynopsis | fieldsynopsis | constructorsynopsis |
destructorsynopsis | methodsynopsis | formalpara | para | simpara | address
| blockquote | graphic | graphicco | mediaobject | mediaobjectco |
informalequation | informalexample | informalfigure | informaltable |
equation | example | figure | table | msgset | procedure | sidebar |
qandaset | task | anchor | bridgehead | remark | highlights | abstract |
authorblurb | epigraph | indexterm | beginpage | xi:include)+ , (refentry*
| section* | simplesect*)) | refentry+ | section+ | simplesect+) , (toc |
lot | index | glossary | bibliography)*), got (title para itemizedlist para
CDATA itemizedlist para para CDATA note )

WTH??? 🤔

**Comment by philipzae** [comment]
I have pending work on this chapter that I need to finalize and submit, so I think we can drop this MR.

**Comment by bluesabre** [comment]
> I have pending work on this chapter that I need to finalize and submit, so I think we can drop this MR.

@philipzae Alrighty, will close it out. @JT252, please follow up with @philipzae to mak sure you're listed as a contributor on chapter 6.

**Pull request closed without merging**
